---
abstract: 'The Ultimate Website Framework'
author:
  - 'Yoran Heling <yorhel@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TUWF
provides:
  TUWF:
    file: lib/TUWF.pm
    version: 0.2
  TUWF::DB:
    file: lib/TUWF/DB.pm
    version: 0.2
  TUWF::Misc:
    file: lib/TUWF/Misc.pm
    version: 0.2
  TUWF::Object:
    file: lib/TUWF.pm
    version: 0
  TUWF::Request:
    file: lib/TUWF/Request.pm
    version: 0.2
  TUWF::Response:
    file: lib/TUWF/Response.pm
    version: 0.2
  TUWF::XML:
    file: lib/TUWF/XML.pm
    version: 0.2
  TUWF::func:
    file: lib/TUWF.pm
    version: 0
recommends:
  DBI: 0
  FCGI: 0
  PerlIO::gzip: 0
requires:
  perl: v5.8.0
resources:
  license: http://opensource.org/licenses/mit-license.php
version: 0.2
